In [1]:
import tensorflow as tf

C:\anaconda\envs\test3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\anaconda\envs\test3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\anaconda\envs\test3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\anaconda\envs\test3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [2]:
from tensorflow import keras

In [3]:
keras.__version__

'2.2.4-tf'

In [4]:
help(keras)

Help on package tensorflow.python.keras.api._v1.keras in tensorflow.python.keras.api._v1:

NAME
    tensorflow.python.keras.api._v1.keras

DESCRIPTION
    # This file is MACHINE GENERATED! Do not edit.
    # Generated by: tensorflow/python/tools/api/generator/create_python_api.py script.

PACKAGE CONTENTS
    activations (package)
    applications (package)
    backend (package)
    callbacks (package)
    constraints (package)
    datasets (package)
    estimator (package)
    experimental (package)
    initializers (package)
    layers (package)
    losses (package)
    metrics (package)
    mixed_precision (package)
    models (package)
    optimizers (package)
    preprocessing (package)
    regularizers (package)
    utils (package)
    wrappers (package)

CLASSES
    tensorflow.python.keras.engine.network.Network(tensorflow.python.keras.engine.base_layer.Layer)
        tensorflow.python.keras.engine.training.Model
            tensorflow.python.keras.engine.sequential.Sequential
 

In [5]:
# 케라스로 신경망 학습 수행
# 1. 데이터 준비
from sklearn.datasets import load_iris

iris = load_iris()
X, y_ori = iris.data, iris.target

In [6]:
# y_origin 정보 변환
from tensorflow.keras.utils import to_categorical

y = to_categorical(y_ori, 3)

In [7]:
# 변환 데이터를 학습용, 검증용 분리
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [11]:
# 2. 인공 신경망 모형 구성
# 노드 8개, 은닉층 1개, 최종출력노드 3개인 출력층 생성
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(units=8, #노드 8개 (마음대로)
                input_dim=4, #입력층 4개 (정해짐-꽃받침 길이&너비)
                kernel_initializer='uniform',
                activation='relu'))
model.add(Dense(units=3, activation='softmax'))

Using TensorFlow backend.


In [12]:
# 3. 모형 학습 과정 설정
model.compile(loss='categorical_crossentropy', # 손실함수 지정
              optimizer='adam', #최적화 기법 지정
              metrics=['accuracy'])

In [13]:
# 설정된 모형 상태 확인
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [14]:
# 4. 모형 학습
model.fit(X_train, y_train,
          epochs=100, #에폭 100
          batch_size=1, #배치 크기 1
          verbose=2)


Epoch 1/100
 - 0s - loss: 1.1060 - accuracy: 0.3143
Epoch 2/100
 - 0s - loss: 1.0633 - accuracy: 0.4095
Epoch 3/100
 - 0s - loss: 1.0244 - accuracy: 0.6952
Epoch 4/100
 - 0s - loss: 0.9660 - accuracy: 0.6952
Epoch 5/100
 - 0s - loss: 0.8795 - accuracy: 0.6952
Epoch 6/100
 - 0s - loss: 0.7901 - accuracy: 0.6952
Epoch 7/100
 - 0s - loss: 0.7045 - accuracy: 0.6952
Epoch 8/100
 - 0s - loss: 0.6252 - accuracy: 0.7333
Epoch 9/100
 - 0s - loss: 0.5732 - accuracy: 0.7429
Epoch 10/100
 - 0s - loss: 0.5254 - accuracy: 0.7429
Epoch 11/100
 - 0s - loss: 0.4822 - accuracy: 0.8095
Epoch 12/100
 - 0s - loss: 0.4527 - accuracy: 0.8762
Epoch 13/100
 - 0s - loss: 0.4272 - accuracy: 0.8381
Epoch 14/100
 - 0s - loss: 0.4076 - accuracy: 0.8762
Epoch 15/100
 - 0s - loss: 0.3847 - accuracy: 0.9048
Epoch 16/100
 - 0s - loss: 0.3676 - accuracy: 0.9333
Epoch 17/100
 - 0s - loss: 0.3561 - accuracy: 0.9048
Epoch 18/100
 - 0s - loss: 0.3347 - accuracy: 0.9048
Epoch 19/100
 - 0s - loss: 0.3227 - accuracy: 0.9429
E

In [16]:
# history 객체에 학습 결과 저장
hist = model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=0)

In [17]:
hist.history['accuracy']

[0.9714286,
 0.9809524,
 0.9714286,
 0.9714286,
 0.9809524,
 0.9714286,
 0.9714286,
 0.9809524,
 0.9714286,
 0.9714286,
 0.9809524,
 0.9809524,
 0.9809524,
 0.9714286,
 0.9714286,
 0.96190476,
 0.9809524,
 0.9809524,
 0.9809524,
 0.9809524,
 1.0,
 0.96190476,
 0.9809524,
 0.9809524,
 0.9809524,
 0.96190476,
 0.9904762,
 0.9809524,
 0.96190476,
 0.9714286,
 0.95238096,
 0.9809524,
 0.9714286,
 0.9809524,
 0.9809524,
 0.9714286,
 0.9809524,
 0.9714286,
 0.9809524,
 0.96190476,
 0.9809524,
 0.9714286,
 0.96190476,
 0.9714286,
 0.9714286,
 0.9809524,
 0.9809524,
 0.9809524,
 0.9714286,
 0.9714286,
 0.9809524,
 0.9714286,
 0.96190476,
 0.9714286,
 0.96190476,
 0.9904762,
 0.9714286,
 0.9714286,
 0.9714286,
 0.9714286,
 0.9714286,
 0.9809524,
 0.9809524,
 0.9714286,
 0.9809524,
 0.9809524,
 0.9714286,
 0.9809524,
 0.9809524,
 0.9904762,
 0.9809524,
 0.9714286,
 0.9714286,
 0.96190476,
 0.9904762,
 0.96190476,
 0.96190476,
 0.9714286,
 0.9714286,
 0.9809524,
 0.9809524,
 0.9809524,
 0.9714286

In [18]:
hist.history['loss']

[0.05820176502374784,
 0.05622834466145191,
 0.06350488387715969,
 0.06368020409479049,
 0.05395763192711512,
 0.053611148382877345,
 0.05311466454927479,
 0.05206928371836434,
 0.0557269579101651,
 0.06013162084273354,
 0.050117353121211274,
 0.05377237415216388,
 0.05110243081428142,
 0.04831016417950031,
 0.055404691606313505,
 0.05874858135838834,
 0.05072616903029318,
 0.050758781097524554,
 0.05580008504215769,
 0.04669635413836184,
 0.03848085685855084,
 0.05539930324629883,
 0.04962930810623943,
 0.05468590453983732,
 0.054407465998321566,
 0.05545239223482552,
 0.05160343237132295,
 0.05532556339226453,
 0.058948893088300536,
 0.04781275767922033,
 0.05991112883222167,
 0.054057317284632034,
 0.0532793539328858,
 0.050055327796030995,
 0.05122512381746506,
 0.05251323126940142,
 0.05504807709878497,
 0.05785256169055467,
 0.04475172352085312,
 0.057784131749178666,
 0.053290510448783565,
 0.05473522352425582,
 0.06151074116960736,
 0.054131460560475846,
 0.05490866703012189,
 

In [19]:
# 5. 모형 성능 평가
loss, acc = model.evaluate(X_test, y_test) # 손실값, 정확도

45/45 [==============================] - 0s 888us/step


In [20]:
print("손실값:", round(loss, 3))
print("정확도:", round(acc, 3))

손실값: 0.084
정확도: 0.978


In [21]:
# 6. 임의의 데이터에 모형 출력 확인
from numpy.random import random
from numpy import round

X_new = round(random([3,4]) * 10, 2)
print(X_new)

[[5.84 2.24 5.5  4.71]
 [4.75 3.37 2.91 6.35]
 [5.8  1.1  0.01 0.68]]


In [22]:
y_pred_class = model.predict_classes(X_new)
print(y_pred_class)

[2 2 0]


In [23]:
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

In [25]:
mnist = fetch_openml('mnist_784', version=1)
X = mnist.data
y_ori = mnist.target.astype(np.int)
y = to_categorical(y_ori, 10)

C:\anaconda\envs\test3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.3, random_state=1)

In [27]:
model = Sequential()
model.add(Dense(input_dim=28*28, units=20, activation='relu'))
model.add(Dense(units=15, activation='relu'))
model.add(Dense(units=10, activation='softmax'))

In [28]:
model.compile(loss='categorical_crossentropy', 
              optimizer=Adam(lr=0.001), # optimizer='adam'
              metrics=['accuracy'])

In [29]:
model.fit(X_train, y_train, epochs=10, batch_size=100, verbose=2,
          validation_data=(X_test, y_test))

Train on 49000 samples, validate on 21000 samples
Epoch 1/10
 - 3s - loss: 3.2532 - accuracy: 0.2910 - val_loss: 1.6515 - val_accuracy: 0.3948
Epoch 2/10
 - 3s - loss: 1.4649 - accuracy: 0.4816 - val_loss: 1.2171 - val_accuracy: 0.6259
Epoch 3/10
 - 3s - loss: 1.0011 - accuracy: 0.6891 - val_loss: 0.8692 - val_accuracy: 0.7291
Epoch 4/10
 - 3s - loss: 0.7809 - accuracy: 0.7653 - val_loss: 0.7426 - val_accuracy: 0.7805
Epoch 5/10
 - 3s - loss: 0.6537 - accuracy: 0.8173 - val_loss: 0.6303 - val_accuracy: 0.8261
Epoch 6/10
 - 3s - loss: 0.5724 - accuracy: 0.8439 - val_loss: 0.5870 - val_accuracy: 0.8486
Epoch 7/10
 - 3s - loss: 0.5237 - accuracy: 0.8583 - val_loss: 0.5343 - val_accuracy: 0.8570
Epoch 8/10
 - 3s - loss: 0.4801 - accuracy: 0.8659 - val_loss: 0.5216 - val_accuracy: 0.8561
Epoch 9/10
 - 3s - loss: 0.4458 - accuracy: 0.8756 - val_loss: 0.4779 - val_accuracy: 0.8719
Epoch 10/10
 - 3s - loss: 0.4194 - accuracy: 0.8847 - val_loss: 0.4639 - val_accuracy: 0.8784


In [30]:
loss, acc = model.evaluate(X_test, y_test)
print(loss)
print(acc)

21000/21000 [==============================] - 1s 33us/step
0.46392944777863365
0.8783809542655945


In [31]:
y_pred = model.predict(X_test)
y_pred_class = model.predict_classes(X_test)

In [32]:
y_test_class = np.argmax(y_test, axis=1)

# y_ori => 2
# y => [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
#       0  1  2  3  4  5  6  7  8  9

In [33]:
print(confusion_matrix(y_test_class, y_pred_class))

[[1908    0   17    2    2   20   62   19   44    2]
 [   2 2234   45    4    2    3   16   11   65    8]
 [  10    3 1806    8   27   11  129   17  108    5]
 [   1    2   49 1787    4  119   15   47  115   26]
 [   3    5   15    0 1817    2   40   11    5  165]
 [  28    4   26   72    9 1690   19   19   32   24]
 [  30    3   72    0   10   24 1848    5    4    3]
 [   4    1    7    5    3    9   15 1964   33  115]
 [   8    5  142    4    7   54   22   42 1730   34]
 [   6    2    3   22  161   21    9  150   20 1662]]


In [34]:
# optimizer = 'adams' 이외에도 'sgd', 'rmsprop'

from keras.optimizers import SGD, RMSprop

In [35]:
help(SGD)

Help on class SGD in module keras.optimizers:

class SGD(Optimizer)
 |  SGD(learning_rate=0.01, momentum=0.0, nesterov=False, **kwargs)
 |  
 |  Stochastic gradient descent optimizer.
 |  
 |  Includes support for momentum,
 |  learning rate decay, and Nesterov momentum.
 |  
 |  # Arguments
 |      learning_rate: float >= 0. Learning rate.
 |      momentum: float >= 0. Parameter that accelerates SGD
 |          in the relevant direction and dampens oscillations.
 |      nesterov: boolean. Whether to apply Nesterov momentum.
 |  
 |  Method resolution order:
 |      SGD
 |      Optimizer
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, learning_rate=0.01, momentum=0.0, nesterov=False, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  get_config(self)
 |  
 |  get_updates(self, loss, params)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from Optimizer:
 |  
 |  g