In [6]:
import sklearn.linear_model as lm

pnn_clf = lm.Perceptron(eta0 = 0.01, max_iter = 1000, tol = 0.001)

In [2]:
import sklearn.datasets as d

dir(d)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_class

In [3]:
iris = d.load_iris()

X = iris.data
y = iris.target

In [7]:
import sklearn.model_selection as ms

X_train, X_test, y_train, y_test = ms.train_test_split(X, y,
                                                      test_size=0.3,
                                                      random_state=0)
clf = pnn_clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

In [8]:
import sklearn.metrics as mt

score = mt.accuracy_score(y_test, y_pred)
print("정확도:",score)

정확도: 0.8


In [9]:
matrix = mt.confusion_matrix(y_test, y_pred)
print(matrix)

[[16  0  0]
 [ 2  9  7]
 [ 0  0 11]]


In [11]:
import sklearn.neural_network as nn

ppn_clf = nn.MLPClassifier(learning_rate_init=0.1,
                          max_iter=1000,
                          activation='relu',
                          hidden_layer_sizes=(50,40,30))

In [12]:
X_train = [[1,2], [5,6], [2,3], [6,7], [3,1], [7,5]]
y_train = [0, 1, 0, 1, 0, 1]

In [13]:
%whos

Variable   Type             Data/Info
-------------------------------------
X          ndarray          150x4: 600 elems, type `float64`, 4800 bytes
X_test     ndarray          45x4: 180 elems, type `float64`, 1440 bytes
X_train    list             n=6
clf        Perceptron       Perceptron(eta0=0.01)
d          module           <module 'sklearn.datasets<...>\\datasets\\__init__.py'>
iris       Bunch            {'data': array([[5.1, 3.5<...>atasets\\data\\iris.csv'}
lm         module           <module 'sklearn.linear_m<...>near_model\\__init__.py'>
matrix     ndarray          3x3: 9 elems, type `int64`, 72 bytes
ms         module           <module 'sklearn.model_se<...>_selection\\__init__.py'>
mt         module           <module 'sklearn.metrics'<...>n\\metrics\\__init__.py'>
nn         module           <module 'sklearn.neural_n<...>al_network\\__init__.py'>
pnn_clf    Perceptron       Perceptron(eta0=0.01)
ppn_clf    MLPClassifier    MLPClassifier(hidden_laye<...>           max_iter=

In [15]:
clf = pnn_clf.fit(X_train, y_train)

In [17]:
X_test = [[1.5, 3.1], [4, 4.5], [6.7, 4.7]]
y_test = [0, 0, 1]

y_pred = clf.predict(X_test)

In [18]:
score = mt.accuracy_score(y_test, y_pred)
print("정확도:",score)

정확도: 0.6666666666666666


In [19]:
matrix = mt.confusion_matrix(y_test, y_pred)
print(matrix)

[[1 1]
 [0 1]]


In [20]:
print(mt.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3



In [30]:
ppn_clf = nn.MLPClassifier(max_iter=1000)
params = {
    'hidden_layer_sizes' : [(100,), (100, 100), (50,), (50, 50)],
    'activation' : ['relu', 'tanh']
}
gs_result = ms.GridSearchCV(ppn_clf, params, n_jobs=-1)
gs_result.fit(X_train, y_train)

GridSearchCV(estimator=MLPClassifier(max_iter=1000), n_jobs=-1,
             param_grid={'activation': ['relu', 'tanh'],
                         'hidden_layer_sizes': [(100,), (100, 100), (50,),
                                                (50, 50)]})

In [31]:
help(ms.GridSearchCV)

Help on class GridSearchCV in module sklearn.model_selection._search:

class GridSearchCV(BaseSearchCV)
 |  GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)
 |  
 |  Exhaustive search over specified parameter values for an estimator.
 |  
 |  Important members are fit, predict.
 |  
 |  GridSearchCV implements a "fit" and a "score" method.
 |  It also implements "score_samples", "predict", "predict_proba",
 |  "decision_function", "transform" and "inverse_transform" if they are
 |  implemented in the estimator used.
 |  
 |  The parameters of the estimator used to apply these methods are optimized
 |  by cross-validated grid-search over a parameter grid.
 |  
 |  Read more in the :ref:`User Guide <grid_search>`.
 |  
 |  Parameters
 |  ----------
 |  estimator : estimator object.
 |      This is assumed to implement the scikit-learn estimator interface.
 |      Either es

In [32]:
gs_result.best_estimator_

MLPClassifier(max_iter=1000)

In [33]:
gs_result.best_params_

{'activation': 'relu', 'hidden_layer_sizes': (100,)}

In [34]:
gs_result.best_score_

0.9714285714285715

In [35]:
mnist = d.fetch_openml('mnist_784', version=1)

In [36]:
dir(mnist)

['DESCR',
 'categories',
 'data',
 'details',
 'feature_names',
 'frame',
 'target',
 'target_names',
 'url']

In [37]:
print(mnist.DESCR)

**Author**: Yann LeCun, Corinna Cortes, Christopher J.C. Burges  
**Source**: [MNIST Website](http://yann.lecun.com/exdb/mnist/) - Date unknown  
**Please cite**:  

The MNIST database of handwritten digits with 784 features, raw data available at: http://yann.lecun.com/exdb/mnist/. It can be split in a training set of the first 60,000 examples, and a test set of 10,000 examples  

It is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image. It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting. The original black and white (bilevel) images from NIST were size normalized to fit in a 20x20 pixel box while preserving their aspect ratio. The resulting images contain grey levels as a result of the anti-aliasing technique used by the normalization algorithm. the images were centered in a 28x28 image b

In [39]:
import numpy as np

X = mnist.data
y = mnist.target.astype('int')

In [38]:
mnist.target[5555]

'7'

In [40]:
X.shape

(70000, 784)

In [41]:
y.shape

(70000,)

In [42]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
X_train, X_test, y_train, y_test = ms.train_test_split(X, y, test_size=0.3)

ppn_clf = nn.MLPClassifier(learning_rate_init=0.001,
                          max_iter=1000,
                          activation='relu',
                          hidden_layer_sizes=(10,10))
clf = pnn_clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("정확도:", mt.accuracy_score(y_test, y_pred))

정확도: 0.8760476190476191


In [44]:
# 정규화
X = X / 255.0

In [45]:
X_train, X_test, y_train, y_test = ms.train_test_split(X, y, test_size=0.3)

ppn_clf = nn.MLPClassifier(learning_rate_init=0.001,
                          max_iter=1000,
                          activation='relu',
                          hidden_layer_sizes=(10,10))
clf = pnn_clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("정확도:", mt.accuracy_score(y_test, y_pred))

정확도: 0.8518095238095238
