In [2]:
from keras.datasets import imdb
from keras.preprocessing import sequence

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)
X_train = sequence.pad_sequences(X_train, maxlen=50)
X_test = sequence.pad_sequences(X_test, maxlen=50)

17465344/17464789 [==============================] - 5s 0us/step


C:\anaconda\envs\test3\lib\site-packages\keras\datasets\imdb.py:101: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
C:\anaconda\envs\test3\lib\site-packages\keras\datasets\imdb.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test, y_test = np.array(xs[idx:]), np.array(labels[idx:])


In [4]:
data = imdb.get_word_index()

1646592/1641221 [==============================] - 2s 1us/step


In [5]:
data2 = {}
for key, value in data.items():
    data2[value+3] = key # data 내에서는 the->1, data2에서는 4->the

In [6]:
for idx, word in enumerate(('<pad', '<sos>', '<unk>')):
    data2[idx] = word

In [9]:
for j in range(5):
    print(' '.join([data2[i] for i in X_train[j]]))
    print()

boat she he should is thought frog but of script you not while history he heart to real at barrel but when from one bit then have two of script their with her nobody most that with wasn't to with armed acting watch an for with heartfelt film want an

senator to <unk> finds tv tend to of emerged these thing wants but <unk> an beckinsale cult as it is video do you david see scenery it in few those are of ship for with of wild to one is very work dark they don't do dvd with those them

isn't one song just is him less are strongly not are you that different just even by this of you there is eight when it part are film's love film's 80's was big also light don't <unk> as it in character looked cinematography so stories is far br man acting

say in can is you for it wasn't in singers as by it away plenty what have reason <unk> are that willing that's have 2 which sister <unk> of important br halfway to of took work 20 br similar more he good flower for hit at coming not see reputation

of <u

In [10]:
for j in range(5):
    print(y_train[j])

1
0
0
1
0


In [11]:
from keras.layers.embeddings import Embedding
from keras.models import Sequential
from keras.layers import LSTM, Dense

model = Sequential()
model.add(Embedding(input_dim = 10000,
                    output_dim = 32,
                    input_length = 50))
model.add(LSTM(units=100))
model.add(Dense(units=1, activation='sigmoid'))

In [12]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [ ]:
model.summary()

In [13]:
model.fit(X_train, y_train,
          epochs=10, batch_size=64, verbose=2)


Epoch 1/10
 - 36s - loss: 0.4767 - accuracy: 0.7618
Epoch 2/10
 - 40s - loss: 0.3297 - accuracy: 0.8570
Epoch 3/10
 - 46s - loss: 0.2762 - accuracy: 0.8869
Epoch 4/10
 - 40s - loss: 0.2317 - accuracy: 0.9072
Epoch 5/10
 - 42s - loss: 0.1850 - accuracy: 0.9291
Epoch 6/10
 - 47s - loss: 0.1433 - accuracy: 0.9458
Epoch 7/10
 - 41s - loss: 0.1093 - accuracy: 0.9622
Epoch 8/10
 - 47s - loss: 0.0831 - accuracy: 0.9707
Epoch 9/10
 - 56s - loss: 0.0608 - accuracy: 0.9798
Epoch 10/10
 - 48s - loss: 0.0507 - accuracy: 0.9833


In [14]:
loss, acc = model.evaluate(X_test, y_test)

25000/25000 [==============================] - 28s 1ms/step 


In [15]:
print('손실값:', round(loss, 3))
print('정확도:', round(acc, 3))

손실값: 0.975
정확도: 0.773


In [16]:
y_pred = model.predict(X_test)
print(y_pred[0:3])

[[0.8606153]
 [0.9986314]
 [0.9221289]]


In [17]:
y_pred_class = model.predict_classes(X_test)
print(y_pred_class[0:3])

[[1]
 [1]
 [1]]


In [67]:
from keras.datasets import reuters

(X_train, y_train), (X_test, y_test) = reuters.load_data(num_words=10000, test_split=0.3)

In [68]:
import numpy as np
np.unique(y_train)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], dtype=int64)

In [69]:
data = reuters.get_word_index()
data

{'mdbl': 10996,
 'fawc': 16260,
 'degussa': 12089,
 'woods': 8803,
 'hanging': 13796,
 'localized': 20672,
 'sation': 20673,
 'chanthaburi': 20675,
 'refunding': 10997,
 'hermann': 8804,
 'passsengers': 20676,
 'stipulate': 20677,
 'heublein': 8352,
 'screaming': 20713,
 'tcby': 16261,
 'four': 185,
 'grains': 1642,
 'broiler': 20680,
 'wooden': 12090,
 'wednesday': 1220,
 'highveld': 13797,
 'duffour': 7593,
 '0053': 20681,
 'elections': 3914,
 '270': 2563,
 '271': 3551,
 '272': 5113,
 '273': 3552,
 '274': 3400,
 'rudman': 7975,
 '276': 3401,
 '277': 3478,
 '278': 3632,
 '279': 4309,
 'dormancy': 9381,
 'errors': 7247,
 'deferred': 3086,
 'sptnd': 20683,
 'cooking': 8805,
 'stratabit': 20684,
 'designing': 16262,
 'metalurgicos': 20685,
 'databank': 13798,
 '300er': 20686,
 'shocks': 20687,
 'nawg': 7972,
 'tnta': 20688,
 'perforations': 20689,
 'affiliates': 2891,
 '27p': 20690,
 'ching': 16263,
 'china': 595,
 'wagyu': 16264,
 'affiliated': 3189,
 'chino': 16265,
 'chinh': 16266,
 '

In [70]:
data3 = {}
for key, value in data.items():
    data3[value+3] = key
data3

{10999: 'mdbl',
 16263: 'fawc',
 12092: 'degussa',
 8806: 'woods',
 13799: 'hanging',
 20675: 'localized',
 20676: 'sation',
 20678: 'chanthaburi',
 11000: 'refunding',
 8807: 'hermann',
 20679: 'passsengers',
 20680: 'stipulate',
 8355: 'heublein',
 20716: 'screaming',
 16264: 'tcby',
 188: 'four',
 1645: 'grains',
 20683: 'broiler',
 12093: 'wooden',
 1223: 'wednesday',
 13800: 'highveld',
 7596: 'duffour',
 20684: '0053',
 3917: 'elections',
 2566: '270',
 3554: '271',
 5116: '272',
 3555: '273',
 3403: '274',
 7978: 'rudman',
 3404: '276',
 3481: '277',
 3635: '278',
 4312: '279',
 9384: 'dormancy',
 7250: 'errors',
 3089: 'deferred',
 20686: 'sptnd',
 8808: 'cooking',
 20687: 'stratabit',
 16265: 'designing',
 20688: 'metalurgicos',
 13801: 'databank',
 20689: '300er',
 20690: 'shocks',
 7975: 'nawg',
 20691: 'tnta',
 20692: 'perforations',
 2894: 'affiliates',
 20693: '27p',
 16266: 'ching',
 598: 'china',
 16267: 'wagyu',
 3192: 'affiliated',
 16268: 'chino',
 16269: 'chinh',
 2

In [71]:
for idx, word in enumerate(('<pad', '<sos>', '<unk>')):
    data3[idx] = word

In [72]:
for j in range(5):
    print(' '.join([data3[i] for i in X_train[j]]))
    print()

<sos> <unk> <unk> said as a result of its december acquisition of space co it expects earnings per share in 1987 of 1 15 to 1 30 dlrs per share up from 70 cts in 1986 the company said pretax net should rise to nine to 10 mln dlrs from six mln dlrs in 1986 and rental operation revenues to 19 to 22 mln dlrs from 12 5 mln dlrs it said cash flow per share this year should be 2 50 to three dlrs reuter 3

<sos> generale de banque sa lt <unk> br and lt heller overseas corp of chicago have each taken 50 pct stakes in <unk> company sa <unk> factors generale de banque said in a statement it gave no financial details of the transaction sa <unk> <unk> turnover in 1986 was 17 5 billion belgian francs reuter 3

<sos> shr 3 28 dlrs vs 22 cts shr diluted 2 99 dlrs vs 22 cts net 46 0 mln vs 3 328 000 avg shrs 14 0 mln vs 15 2 mln year shr 5 41 dlrs vs 1 56 dlrs shr diluted 4 94 dlrs vs 1 50 dlrs net 78 2 mln vs 25 9 mln avg shrs 14 5 mln vs 15 1 mln note earnings per share reflect the two for one split

In [73]:
from keras.preprocessing import sequence

X_train = sequence.pad_sequences(X_train, maxlen=100)
X_test = sequence.pad_sequences(X_test, maxlen=100)

from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train) # 훈련용 뉴스 기사 레이블의 원-핫 인코딩
y_test = to_categorical(y_test) 

In [74]:
for j in range(5):
    print(y_train[j])

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [83]:
from keras.layers.embeddings import Embedding
from keras.models import Sequential
from keras.layers import LSTM, Dense

model = Sequential()
model.add(Embedding(input_dim = 10000,
                    output_dim = 32,
                    input_length = 100)) # X_train과 같이 100으로 맞춰야함
model.add(LSTM(units=100))
model.add(Dense(units=46, activation='softmax'))

In [84]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [85]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 100, 32)           320000    
_________________________________________________________________
lstm_10 (LSTM)               (None, 100)               53200     
_________________________________________________________________
dense_10 (Dense)             (None, 46)                4646      
Total params: 377,846
Trainable params: 377,846
Non-trainable params: 0
_________________________________________________________________


In [86]:
model.fit(X_train, y_train,
          epochs=10, batch_size=100, verbose=2)

Epoch 1/10
 - 22s - loss: 2.4568 - accuracy: 0.3620
Epoch 2/10
 - 20s - loss: 2.0572 - accuracy: 0.4727
Epoch 3/10
 - 22s - loss: 1.8878 - accuracy: 0.4994
Epoch 4/10
 - 32s - loss: 1.7669 - accuracy: 0.5319
Epoch 5/10
 - 24s - loss: 1.6932 - accuracy: 0.5522
Epoch 6/10
 - 22s - loss: 1.5963 - accuracy: 0.5745
Epoch 7/10
 - 25s - loss: 1.5256 - accuracy: 0.5938
Epoch 8/10
 - 26s - loss: 1.4380 - accuracy: 0.6129
Epoch 9/10
 - 24s - loss: 1.3634 - accuracy: 0.6320
Epoch 10/10
 - 26s - loss: 1.2986 - accuracy: 0.6536


In [87]:
loss, acc = model.evaluate(X_test, y_test)

3369/3369 [==============================] - 5s 1ms/step


In [88]:
print('손실값:', round(loss, 3))
print('정확도:', round(acc, 3))

손실값: 1.708
정확도: 0.568


In [89]:
y_pred = model.predict(X_test)
print(y_pred[0:3])

[[3.7977449e-03 4.1155089e-03 3.8866284e-03 5.6773585e-01 9.7970013e-03
  7.7570055e-04 6.3735568e-03 1.3002482e-02 3.1547572e-02 3.3110576e-03
  7.2462186e-03 1.0997964e-02 1.3198799e-02 1.1713137e-03 2.6277648e-03
  2.2404364e-03 6.3718399e-03 1.4962739e-03 1.9846244e-02 8.6817071e-03
  4.5780325e-03 4.3438643e-02 1.7366072e-03 1.0014918e-02 2.0678425e-03
  7.7666179e-03 3.5733066e-03 1.7825492e-03 4.4307224e-03 2.2654207e-02
  3.1852204e-02 6.8431706e-03 4.5232368e-03 2.3707955e-03 6.5754674e-02
  3.4242768e-03 2.6416555e-02 4.4653215e-03 8.8232616e-03 4.2052558e-03
  7.1242999e-04 6.9547314e-03 1.2948486e-03 7.4295555e-03 2.7774784e-03
  1.8868364e-03]
 [1.1122522e-04 1.0640203e-03 1.2121805e-04 9.6251267e-01 9.9212322e-03
  1.2461167e-05 2.2697497e-04 1.1977794e-04 4.0996727e-03 2.4783984e-04
  4.8626954e-04 1.9989519e-03 7.6455425e-04 3.5872729e-04 2.4962781e-05
  4.8045906e-05 4.4461605e-03 3.3724142e-04 2.6770472e-04 3.3525107e-03
  1.3783110e-03 1.9173520e-03 1.4982392e-05 8.1

In [90]:
y_pred_class = model.predict_classes(X_test)
print(y_pred_class[0:3])

[ 3  3 16]
